version: '2'
services:
    db:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: toor
        volumes:
            - /opt/trendfa-mysql:/var/lib/mysql
        ports:
            - "13306:3306"

    trendfa:
        build: .
        volumes:
          - .:/src
        links:
          - db:mysql

