version: '2'
services:
    db:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: toor
    
    trendfa:
        build: .
        volumes:
          - .:/src
        links:
          - db:mysql

